# Generated by Django 4.2.5 on 2024-10-22 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0004_mymodel_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(max_length=100, verbose_name="合同编号"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="合同金额"
                    ),
                ),
                ("sign_date", models.DateField(verbose_name="签订日期")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "有效"), ("inactive", "无效")],
                        max_length=50,
                        verbose_name="合同状态",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "合同",
                "verbose_name_plural": "合同管理",
            },
        ),
    ]
