# Generated by Django 4.2.5 on 2024-10-22 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="contract_number",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="sign_date",
        ),
        migrations.RemoveField(
            model_name="contract",
            name="status",
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="合同金额"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_name",
            field=models.CharField(
                default="未命名合同", max_length=255, verbose_name="合同名称"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contract",
            name="signed_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="签署日期"
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
