# Generated by Django 4.2.5 on 2024-10-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_delete_mymodel_remove_contract_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(default="active", max_length=20, verbose_name="状态"),
        ),
    ]
