# Generated by Django 4.2.5 on 2024-10-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0003_contract_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_number",
            field=models.CharField(default="未定义", max_length=100, verbose_name="合同编号"),
        ),
    ]
