# Generated by Django 4.2.5 on 2024-09-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="项目名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="项目描述"),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目管理",
            },
        ),
    ]
