# Generated by Django 4.2.5 on 2024-09-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_alter_customer_options_alter_customer_address_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AddField(
            model_name="project",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(),
        ),
    ]
