# Generated by Django 4.2.5 on 2024-09-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0003_alter_customer_address_alter_customer_company_size_and_more",
        ),
        ("projects", "0002_alter_project_options_project_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="客户",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="项目描述"),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="结束日期"),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255, verbose_name="项目名称"),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(verbose_name="开始日期"),
        ),
    ]
