# Generated by Django 4.2.5 on 2024-10-22 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_mymodel_alter_customer_options_and_more"),
        ("projects", "0003_alter_project_customer_alter_project_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "项目", "verbose_name_plural": "项目管理"},
        ),
        migrations.RemoveField(
            model_name="project",
            name="description",
        ),
        migrations.RemoveField(
            model_name="project",
            name="name",
        ),
        migrations.AddField(
            model_name="project",
            name="hours_invested",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="投入工时"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_name",
            field=models.CharField(default=0, max_length=100, verbose_name="项目名称"),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("ongoing", "进行中"), ("completed", "已完成")],
                default=0,
                max_length=50,
                verbose_name="项目状态",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="customer",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="客户",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="项目结束时间"),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(verbose_name="项目开始时间"),
        ),
    ]
