# Generated by Django 4.2.5 on 2024-10-22 07:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_delete_mymodel_alter_customer_options_and_more"),
        ("projects", "0004_mymodel_alter_project_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
        migrations.RemoveField(
            model_name="project",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="hours_invested",
        ),
        migrations.RemoveField(
            model_name="project",
            name="start_date",
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="total_hours",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="项目总投入工时"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="project",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.customer",
                verbose_name="客户",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(
                default="未命名项目", max_length=255, verbose_name="项目名称"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(default="进行中", max_length=50, verbose_name="项目状态"),
        ),
    ]
