# Generated by Django 4.2.5 on 2024-09-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="客户名称")),
                (
                    "contact_person",
                    models.CharField(max_length=255, verbose_name="联系人"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="联系邮箱"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                ("address", models.CharField(max_length=255, verbose_name="地址")),
                (
                    "company_size",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="公司规模"
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="行业"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "客户",
                "verbose_name_plural": "客户管理",
            },
        ),
    ]
