# Generated by Django 4.2.5 on 2024-09-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={},
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="company_size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="contact_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="customer",
            name="contact_person",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
