# Generated by Django 4.2.5 on 2024-10-22 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "customers",
            "0003_alter_customer_address_alter_customer_company_size_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "客户管理", "verbose_name_plural": "客户管理"},
        ),
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="company_size",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="contact_person",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="customer",
            name="completed_receivable_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="已完成待收款金额"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="contract_count",
            field=models.IntegerField(default=0, verbose_name="已签订合同数量"),
        ),
        migrations.AddField(
            model_name="customer",
            name="cooperation_start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="合作开始时间"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="current_project_count",
            field=models.IntegerField(default=0, verbose_name="当前项目数量"),
        ),
        migrations.AddField(
            model_name="customer",
            name="current_project_hours",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="当前项目投入工时"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="presales_project_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="售前项目金额"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="total_contract_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="累计合同总额"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(default="未知客户", max_length=100, verbose_name="客户名称"),
        ),
    ]
