# Generated by Django 4.2.5 on 2024-10-22 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0004_mymodel_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "客户", "verbose_name_plural": "客户管理"},
        ),
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="cooperation_start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="合作开始时间"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(
                default="未命名客户", max_length=255, verbose_name="客户名称"
            ),
        ),
    ]
