# Generated by Django 4.2.5 on 2024-10-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0005_delete_mymodel_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.CharField(default="active", max_length=20, verbose_name="状态"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
