# Generated by Django 4.2.5 on 2024-10-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0006_customer_status_alter_customer_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="level",
            field=models.CharField(default="普通", max_length=50, verbose_name="级别"),
        ),
        migrations.AddField(
            model_name="customer",
            name="province",
            field=models.CharField(default="未知", max_length=100, verbose_name="省份"),
        ),
    ]
