# Generated by Django 4.2.5 on 2024-09-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_code",
                    models.CharField(max_length=255, verbose_name="审批编号"),
                ),
                (
                    "approval_name",
                    models.CharField(max_length=255, verbose_name="审批名称"),
                ),
                ("applicant", models.CharField(max_length=255, verbose_name="申请人")),
                ("status", models.CharField(max_length=50, verbose_name="审批状态")),
                ("create_time", models.DateTimeField(verbose_name="创建时间")),
            ],
            options={
                "verbose_name": "审批流程",
                "verbose_name_plural": "审批流程管理",
            },
        ),
    ]
