# Generated by Django 4.2.5 on 2024-10-22 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customers", "0004_mymodel_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="PresalesProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100, verbose_name="项目名称")),
                (
                    "project_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="项目金额"
                    ),
                ),
                (
                    "project_status",
                    models.CharField(
                        choices=[("ongoing", "进行中"), ("completed", "已完成")],
                        max_length=50,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                        verbose_name="客户",
                    ),
                ),
            ],
            options={
                "verbose_name": "售前项目",
                "verbose_name_plural": "售前项目管理",
            },
        ),
    ]
