# Generated by Django 4.2.5 on 2024-09-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taskms", "0002_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                default="默认任务名称", max_length=100, unique=True, verbose_name="任务名称"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(
                default="默认任务标题", max_length=255, verbose_name="任务标题"
            ),
        ),
    ]
